trunk-version = "^0.21.7"

[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = ["."]

[build]
target = "./index.html"
dist = "../dist"

[serve]
port = 1420
open = false
ws_protocol = "ws"

[watch]
watch = ["../../../crates/sys/src", "./src/**/*.module.scss", "./src/**/*.module.css"]